[zabbix_server]
zbx-server ansible_host=192.168.0.119

[zabbix_proxies]
zbx-proxy ansible_host=192.168.0.121 ansible_user=zabbix

[zabbix_agents]
zbx-agent ansible_host=192.168.0.126 ansible_user=usuario

[windows]
zbx-win ansible_host=192.168.0.130
zvb-win2 ansible_host=

[zabbix_windows_server]
zbx-win-serv ansible_host=192.168.0.132

[debian]
zbx-debian ansible_host=