ansible_connection: winrm
ansible_port: 5985
ansible_winrm_transport: ntlm
ansible_winrm_server_cert_validation: ignore
ansible_user: zabbix
ansible_password: Sip@@343004
zabbix_proxy_ip: "192.168.0.121"
zabbix_proxy_name: "zbx-proxy"
